version: "3"
services:
    starwars-db:
        image: "mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04"
        container_name: "starwars-db"
        ports:
            - "1435:1433"
        volumes: 
            - sqlsystem:/var/opt/mssql/
            - sqldata:/var/opt/sqlserver/data
            - sqllog:/var/opt/sqlserver/log
            - sqlbackup:/var/opt/sqlserver/backup
        environment:
            SA_PASSWORD: "dev@1234"
            ACCEPT_EULA: "Y"

    starwars:
        container_name: "starwars"
        build: 
            context: .
            dockerfile: ./Api.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - DB_CONNECTION_STRING=Server=starwars-db;Database=starwars;User=sa;Password=dev@1234
        ports: 
            - "8082:5001"
        networks:
            default:
                aliases: 
                    - starwars.api
        depends_on: 
            - starwars-db
volumes:
    sqlsystem:
    sqldata:
    sqllog:
    sqlbackup: